services:
  ac-front:
    build: ./AC-Front
    ports:
      - "3000:3000"
    depends_on:
      - ac-back
    networks:
      - ac-network

  ac-back:
    build: ./AC-Back
    ports:
      - "8080:8080"
    env_file:
      - ./AC-Back/ac-back-db.env
    networks:
      - ac-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ac-front
      - ac-back
    networks:
      - ac-network

networks:
  ac-network:
    driver: bridge