services:
  ac-front:
    build: ./AC-Front
    ports:
      - "80"
    depends_on:
      - ac-back

  ac-back:
    build: ./AC-Back
    ports:
      - "8080"
    env_file:
      - ./AC-Back/ac-back-db.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ac-front
      - ac-back