services:
  ac-front:
    build: ./AC-Front
    ports:
      - "80:80"
    depends_on:
      - ac-back
    networks:
      - ac-network

  ac-back:
    build: ./AC-Back
    ports:
      - "8080:8080"
    env_file:
      - ./AC-Back/ac-back-db.env
    networks:
      - ac-network

networks:
  ac-network: